.eslintrc
app/assets/javascripts/admin.js
app/assets/javascripts/application.js
app/assets/javascripts/dispatcher.js
app/assets/javascripts/management.js
app/assets/javascripts/routers/AdminRouter.js
app/assets/javascripts/routers/ManagementRouter.js
app/assets/javascripts/views/admin/adminView.js
app/assets/javascripts/views/home/homeView.js
app/assets/javascripts/views/management/managementView.js
package.json

At first, I was unable to configure eslint to use [Airbnb's ES5 configuration](https://www.npmjs.com/package/eslint-config-airbnb-base) but I finally managed to add it. The main reason of this PR is that the eslint's recommended configuration is too permissive and doesn't check much.
I've updated the current code so only warnings are left due to the `console.log` statements which will be removed in the future.

Adds Airbnb's ES5 configuration for eslint

---

app/assets/javascripts/dispatchers/frontDispatcher.js
app/assets/stylesheets/components/front/c-content.scss
app/assets/stylesheets/components/front/c-cover.scss
app/assets/stylesheets/front/_base-theme-2.scss
app/assets/stylesheets/front/_settings-theme-1.scss
app/assets/stylesheets/front/_settings-theme-2.scss
app/views/layouts/application.html.erb

The PR makes some changes to the public websites due to design changes or visual/functional issues.
Here's the full list of changes:
* Reduces the padding of the wrapper on desktop (according to the new visuals)
* Reduces the max-size of the images (to match the design)
* Removes the `display: inline-block;` property on the links of theme 2 because it would prevent them to break on a new line
* On mobile, increases the top padding of the cover component to have more space with the breadcrumbs
* Fixes an issue with the routers where the JS wouldn't execute due to another running instance of `Backbone.History`

Brings modifications to the public sites

---

app/assets/javascripts/templates/management/site-switcher.hbs
app/assets/javascripts/views/management/siteSwitcherView.js

This PR makes the site switcher more resilient but less compliant with the design.
In the design, the site switcher's width is equal to it's content i.e. the length of the selected site name.
Nevertheless, as it's impossible to do so in pure CSS, the previous solution was setting the width of the input to a fixed size (the length of its content) using the [`ch` CSS unit](https://www.w3.org/TR/css3-values/#ch) (1 ch is fairly equivalent at the size of a character).
The solution was tricky due to the fairness of the equivalence and caused an issue on Chromium on Linux where the input wouldn't be wide enough to show its full content. As a consequence, this PR rolls back the code to let the input's width be the size of the longer option.

Doesn't force the width anymore

---

app/views/management/site_pages/forms/_open_content.html.erb
app/views/management/site_pages/forms/_static_content.html.erb

PR #69 has been merged quickly without testing (my fault). Some references to `ckeditor` were still present which would raise internal errors when the user would create or edit pages that contain a `textarea` (Open Content page for example).

Fixes a 500 error when creating/editing a page

---

app/controllers/management/site_pages_controller.rb
app/controllers/management/static_page_controller.rb
app/controllers/management_controller.rb

Admin users can now access all sites on the management interface, even if they are not explicitly associated to them

Improve authorization on management interface

---

app/controllers/application_controller.rb

There was a bug when rendering the layout for the site's pages when the user was logged in.
Please check if this fix is correct.

Bug fix: pages layout doesn't render admin layout when logged in

---

app/controllers/site_page_controller.rb
app/models/page.rb
app/views/front/_menu.html.erb

Invisible pages won't be shown in the menu nor when accessed directly.

Implemented visible/unvisible for the sites' pages

---

app/assets/javascripts/views/shared/tableView.js

This PR prevents the table's search field to be duplicated when the user push the browser's back button.
The issue is caused by [Turbolinks](https://github.com/turbolinks/turbolinks) caching the page and can be solved by making sure to empty the container of the search field before adding a new one.
[Pivotal task](https://www.pivotaltracker.com/story/show/133613407)

Prevents the search field to be duplicated

---

app/assets/javascripts/routers/front/DashboardRouter.js
app/assets/javascripts/templates/front/dashboard-filters.hbs
app/assets/javascripts/views/front/dashboardFiltersView.js
app/assets/stylesheets/components/shared/c-select.scss
app/assets/stylesheets/layouts/front/l-analysis-dashboard.scss
app/views/site_page/analysis_dashboard.html.erb

This PR adds simple filters to the dashboard. With them, the user can fix a specific value to a column and see the result on the charts that update automatically. They are also stored in the global state (and thus the URL and the bookmarks) so they can be restored later.
Until we have detailed designs, feedback from the client and know what's possible with the dataset API, the filters will keep being simple.
**NOTE:** As the rest of the dashboard, the dates are not supported yet.

Simple filters for the analysis dashboard

---

.eslintrc
Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/assets/javascripts/routers/front/DashboardRouter.js
app/assets/javascripts/views/shared/mapWidgetView.js
app/assets/stylesheets/components/front/c-map-widget.scss

This PR makes implements the map on the dashboard.
It displays the rows as dots and when the user clicks on them, a popup with all the data is opened. Because the number of dots can be high, they are grouped as cluster.
NOTE: for now, the map will display the rows who have fields called `latitude` and `longitude`. Once the logic is built in the back end and the management section, this limit will be removed.

Implements the map on the dashboard

---

Gemfile
Gemfile.lock
app/assets/javascripts/helpers/handlebars.js
app/assets/javascripts/management.js
app/assets/javascripts/routers/management/FiltersStepRouter.js
app/assets/javascripts/templates/management/dashboard-filters.hbs
app/assets/javascripts/views/management/dashboardFiltersView.js
app/assets/javascripts/views/shared/modalView.js
app/assets/stylesheets/_base.scss
app/assets/stylesheets/components/management/c-dashboard-filters.scss
app/assets/stylesheets/components/shared/c-modal.scss
app/assets/stylesheets/layouts/management/l-page-creation.scss
app/assets/stylesheets/management/application.scss
app/controllers/management/page_steps_controller.rb
app/models/dataset_setting.rb
app/views/management/page_steps/_footer.html.erb
app/views/management/page_steps/columns.html.erb
app/views/management/page_steps/filters.html.erb

This PR implements the code for the filters step of the dashboard creation/edition as well as adds its styles.
The manager can select some fields from the dataset and filter them depending on their type:
* for numbers, a min and a max selectors are available
* for dates, we have the same selectors but with date pickers
* for strings, we have a selector where they can select as much (real) values (from the dataset) as they want
Any other type of column is hidden. Please also note the the handling of the dates is still not perfect as we don't have a standardised way to retrieve them from the API.
In addition to filtering the dataset, the manager can also indicate which fields the end user will be able to use as filters on the analysis dashboard.
@santostiago, before merging, please make …

Implements and styles the filters step

---

app/controllers/admin_controller.rb
app/controllers/application_controller.rb
app/controllers/auth_controller.rb
app/helpers/auth_helper.rb
app/helpers/permissions_helper.rb
config/application.rb

Currently we validate the user's auth status on the API in every request. This makes the internet very sad because:
- We don't really need to validate every single request.
- API-side, this does not scale - it's a bunch of useless requests
- CMS-side, this adds a lot of unnecessary delay.
- Every API hiccup is visible on the CMS.
So, I added a TTL to it. Basically, with the current config, we only validate the authentication once every 10 minutes. Going live we might lower this to 1m or 30 seconds.

Session revalidation TTL

---

lib/tasks/sample.rake

We haven't been able to go to `/management` after API login because the user wasn't added to the sample data.
So this PR adds Clara and Jose Angel users

Add Clara and Jose Angel as user

---

app/assets/javascripts/views/management/dashboardFiltersView.js
app/assets/stylesheets/components/shared/c-table.scss

Add `Table preview shows only 10 first rows` legend in filters preview table and fix dashed rows in tables.

Table preview legend

---

.eslintrc
app/assets/javascripts/dispatchers/managementDispatcher.js
app/assets/javascripts/routers/management/MapStepRouter.js
app/assets/stylesheets/components/shared/c-inputs-container.scss
app/assets/stylesheets/layouts/management/l-page-creation.scss
app/views/layouts/management.html.erb
app/views/management/page_steps/map.html.erb

This PR makes the edition of the standalone map's configuration easier by adding syntax highlighting. In addition, the styles have been unified with the rest of the flows.
Please, try to fix [this issue](https://www.pivotaltracker.com/story/show/136964993) before merging the PR as it could be harder to debug it.
This PR doesn't have any attached Pivotal task.

Adds syntax highlighting to the map's configuration

---

app/assets/javascripts/blots/imageBlock.es6
app/assets/javascripts/blots/imageBlock.js
app/assets/javascripts/helpers/notifications.js
app/assets/javascripts/views/shared/wysiwygView.js
app/assets/stylesheets/components/management/c-wysiwyg.scss

This PR prevents the upload of large images through the wysiwyg. The main reason is that the browser would eventually crash when adding several images in the same page.
To reduce their file size, each image is encoded to base64 (as before), then scaled down and rendered in a hidden canvas and finally re-encoded as base64. The default params force the images to fit into a box of the size 1060x600px.
As an example, with [this image of a cute 🐶](https://unsplash.com/collections/380/petunia-the-pug?photo=2Ts5HnA67k8), which weights 5MB, the final base64-encoded version weights only 1/3 of the original. Obviously, the ratio will depend on the size of the original image.
In addition to this feature, the PR prevents the user from adding text within the image container and the wysiwyg handles the …

Reduces the size of the images uploaded via the wysiwyg

---

CHANGELOG.md
app/assets/javascripts/views/shared/wysiwygView.js
app/assets/stylesheets/components/management/c-wysiwyg.scss
app/assets/stylesheets/components/shared/c-content.scss
app/views/layouts/management.html.erb

This PR adds three new formatting options for the wysiwyg:
- alignment (left, centre and right)
- indentation (left and right)
- lists (bullet and ordered)
In addition, the [Quill.js' version](https://github.com/quilljs/quill/releases/tag/v1.2.0) has been updated and a previous unused library has been removed.

New formatting options for the wysiwyg

---

app/assets/javascripts/dispatchers/frontDispatcher.js

This PR fixes an issue that could prevent the dashboard from loading correctly.
Basically, when switching the Backbone router's `pushState` state from `true` to `false` (by stopping it and restarting it), some asynchronous events could still be dispatched and the routes could be executed twice. In some cases, this would just throw an error in the console, but in other, the dashboard wouldn't load at all (on FF only).

Fixes a bug where the router could instance twice the same views

---

CHANGELOG.md
app/assets/stylesheets/components/front/c-cover.scss

This PR removes the veil from the landscape theme.  I'm not sure this is whats asked for because this was expected behaviour, not a bug.

removes the veil from the lanscape theme

---

CHANGELOG.md
app/assets/stylesheets/components/front/c-cover.scss

This PR changes color and decoration of cover-attribution links.
```
color: white;
text-decoration: none (underlined on hover);
background-color: none
```

Fix: cover attribution styles

---

app/assets/javascripts/blots/widgetBlock.es6
app/assets/javascripts/blots/widgetBlock.js
app/assets/javascripts/routers/management/OpenContentStepRouter.js
app/assets/javascripts/routers/management/VisualizationStepRouter.js
app/assets/javascripts/views/management/widgetsModalView.js

This PR fixes issue where creating charts from _gon_ stored data crashed. 
This was due to a schema change in the widget object. Before all widgets where charts and a widget's type was a chart's type. Now there's also map widgets and so the chart's type is no longer stored at `widget.type` but in `widget.chart` instead. This PR fixes that and also adds compatibility for legacy widget charts.

fixes reading of gon widgets

---

app/assets/javascripts/templates/admin/urls-input.hbs
app/assets/javascripts/views/admin/urlsInputView.js

This PR hides the default empty input on the `urlInputView` thus only showing if you click in the Add Url button.

fix: hide url input view placeholder

---

CHANGELOG.md
app/models/page_template.rb
app/models/site.rb
app/models/site_setting.rb
app/models/template_renderer.rb
app/services/site_creator.rb
app/views/admin/site_steps/settings.html.erb
app/views/front/_footer.html.erb
db/migrate/20170324120306_update_terms_page_template.rb
db/schema.rb
lib/assets/terms_template.json
lib/assets/terms_template.json.erb
lib/tasks/sample.rake
lib/tasks/update_site_settings.rake

- Template for "Terms of Service" page is store in a .json.erb file, to facilitate injecting the hosting organization variable
- A new site setting has been added to store the hosting organization
- Logic in place to rebuild the "Terms of Service" page when the hosting organization is updated
- `rake db:migrate` to update existing sites

Updated Terms of Service page template

---

CHANGELOG.md
app/assets/stylesheets/components/shared/c-select.scss
app/controllers/admin/site_steps_controller.rb
app/controllers/site_page_controller.rb
app/models/site_setting.rb
app/views/admin/site_steps/settings.html.erb
app/views/layouts/application.html.erb
lib/tasks/update_site_settings.rake

Adds an option to the site settings to configure the site's default language
ToDo: review styling on new site setting

Add config option for site default language

---

app/assets/javascripts/templates/front/dashboard-bookmarks.hbs
app/assets/stylesheets/components/shared/c-dashboard-bookmarks.scss

- When adding many bookmarks to the bookmark bar, the ones that were added first wouldn't be reachable cause the container did not grow appropriately. This has been changed so now the container will grow as big as it's needed and all bookmarks are reachable.
- The scroll bar would always appear on Linus/Windows OS because the overflow prop was set to `overflow-x: scroll;` instead of `overflow-x: auto;`.
This PR tackles issues mentioned in #194

Fix: dashboard bookmark bar

---

app/assets/javascripts/routers/management/PreviewStepRouter.js
app/assets/javascripts/views/shared/chartWidgetView.js
app/assets/stylesheets/components/shared/c-fieldset.scss

- In the site's management, when editing a dashboard the previously set widgets' labels would not appear. This was due to the fact that the `xLabel` and `yLabel` props were not being passed on widget's init. This has been solved. (Mentioned before in #194 )
- When displaying a widget that only had one axis both the x and y axes inputs were displayed. Now if there's only one axis, we display only one input, and change the placeholder accordingly.

Fix: dashboard preview missing axes label values

---

app/assets/javascripts/routers/management/StructureRouter.js
app/controllers/management/site_pages_controller.rb
app/helpers/tree_structure_helper.rb
app/models/page.rb

fix: site structure deletion

---

app/assets/javascripts/routers/management/PositionStepRouter.js

- removes slashed eye icon in disabled pages because it raised confusion sometimes.

fix position step tree icon

---

app/assets/javascripts/routers/front/DashboardRouter.js
app/assets/javascripts/routers/management/PreviewStepRouter.js
app/assets/javascripts/routers/management/VisualizationStepRouter.js

This PR includes the following:
- Reads the geo location fields of the dataset, provided by gon's legend prop.
- Renders the dashboard's map widgets with the provided geo field in management and front.

Feat: dashboard dataset geo fields

---

app/assets/javascripts/dispatchers/frontDispatcher.js
app/assets/javascripts/views/front/languageSelectorView.js
app/assets/javascripts/views/shared/dropdownSelectorView.js
app/assets/stylesheets/components/front/c-header.scss
app/views/front/_menu.html.erb

This PR includes the following:
- Inits the language selector on the mobile drawer.
- Updates `DropdownSelector` to include `setActive` to its API.
- Updates `LanguageSelector` to include `updateCurrentLanguage` and `useShortName` to its API.
- Listens to changes between language selectors to maintain them in sync.
- Fixes hamburguer menu disappearing in mobile drawer when scrolling.

Fix: mobile drawer lang select

---

app/assets/javascripts/helpers/handlebars.js
app/assets/javascripts/templates/front/charts/pie.hbs
app/assets/javascripts/templates/front/charts/vegaTheme.hbs

- When selecting a column with many different values, the pie chart would break. Now we only display the top 4 classes and a 5 one named `other` than summarises the rest.

fix: pie chart classes

---

CHANGELOG.md
app/models/site_setting.rb

This affected sites where no settings were set in the `style` step when creating the site. Upon editing, the style step was a blank page.

Fixed condition used to check if settings need initializing

---

app/assets/javascripts/views/shared/userLinksView.js
app/controllers/admin_controller.rb
app/controllers/application_controller.rb
app/controllers/auth_controller.rb
app/controllers/management/profile_controller.rb
app/controllers/management_controller.rb
app/controllers/static_page_controller.rb
app/helpers/auth_helper.rb
app/helpers/permissions_helper.rb

In relation to this:
https://www.pivotaltracker.com/story/show/137809425
In fact there were two conditions under which the app would enter an infinite redirect loop:
- user logged in successfully using an email address that is not registered in the CMS
- user logged in successfully with a social media account
In the first case the user is informed their account in the CMS might not be set up properly. In the latter, they are informed they should log in using their email (for that to happen, they need to log out first using the API gateway)

Breaks infinite redirect loop when login via social media or unrecognised email

---

app/models/site_page.rb

Adjust position of siblings who follow or precede the inserted / moved node before closure_tree updates all positions and messes up the order.
https://www.pivotaltracker.com/story/show/136244263

Fix for page positions off by one

---

app/assets/javascripts/routers/front/DashboardRouter.js

- Only listen to filter changes if there are filters, avoiding a re-render.

Fix: avoid unnecessary re renders

---

app/controllers/management/widget_steps_controller.rb
app/services/dataset_service.rb

Fixes an issue with `float` and `text` fields types when creating widgets. When selected in the list of columns, no dropdowns / inputs would appear to select from existing values, because those data types were previously not mapped to the numeric & string types in the CMS.

Fix for populating the list of values for float and text fields

---

app/services/dataset_service.rb

Fixes https://basecamp.com/1756858/projects/12384525/todos/306054528
Some datasets were probably registered in the early days for an application called "prep". The list of datasets available for widget / dashboard creation is filtered by application name, currently "forest-atlas". The easiest thing to do was to include the "prep" application in the filter.

Include datasets registered for "prep" application

---

app/assets/javascripts/views/shared/wysiwygView.js

This PR addresses the following issue:
- When changing language on pages where the `wysiwygView` was instanciated, an infinite loop occurred because both `quill.js` and `transifex.live.js` where reacting to the other library's events. This PR fixes this issue by removing all of quill's event listeners when `readOnly: true` and cloning the dom node.

fix: prevents infinite event loop cause by quill + transifex

---

CHANGELOG.md
app/controllers/admin/site_steps_controller.rb

The issue: user uploads images (logo, cover) and those don't get saved\
Reason: relevant site settings don't exist; validation rules prevent from saving a site setting with empty value for images
Solution: just create those settings on demand if user uploads images
Also, added a `rescue` to the surely well-intentioned `begin`.

If site setting does not exist, create it to save uploaded images

---

.env.sample
app/helpers/permissions_helper.rb
app/javascript/components/containers/shared/AdminContainer.js
app/javascript/components/containers/shared/PublicContainer.js
app/javascript/components/redactions/admin.js
app/javascript/components/redactions/env.js
app/javascript/components/reducers/index.js

**env** is now going to be available in the redux admin, with useful environment variables, also adding the **token** if we want to send any requests. 
Example of data we are sending now from rails to redux

add env vars to admin redux store

---

app/assets/stylesheets/components/shared/c-steps-bar.scss
app/javascript/components/StepsBar.js

This PR adds a new React component ,`StepsBar`, based on the HTML/Rails component we've been using.
The user has the possibility to click on the previous steps to go back to them but not to jump forward.
PS: this component will be used in the widget creation.

Migrate the StepsBar component to React

---

db/migrate/20180427122058_add_dashboard_version_to_pages.rb
db/schema.rb

The user needs to be available to choose a dashboard version, as we are keeping the old dashboard. 
This will add a new field to the pages table so we can keep track of it, 
for now, it will default to the first version.

add migration for pages, dashboard version

---

app/assets/stylesheets/components/management/c-add-widgets.scss
app/controllers/management/page_steps_controller.rb
app/controllers/static_page_controller.rb
app/javascript/components/wysiwyg/WidgetBlock.js
app/javascript/components/wysiwyg/WidgetBlockCreation.js
app/javascript/components/wysiwyg/index.js
app/javascript/pages/admin/edit-dashboard.js
app/views/management/page_steps/title.html.erb

1. New wysiwyg renders the widget editor created widgets! and supports the vega3 syntax
2. Widget output now changed, also supporting widget editor syntax
New option added to wysiwyg
List of widgets you can select, based on the new widget editor

Widgets fixes

---

app/assets/javascripts/routers/management/DatasetStepRouter.js
app/assets/javascripts/views/shared/quickLinksView.js
app/assets/javascripts/views/shared/tabView.js
app/assets/javascripts/views/shared/userLinksView.js
app/views/admin/_header.html.erb
app/views/management/_header.html.erb

Turbolinks causes the tables to not render, this makes sure we do a full reload, so webpacker can trigger react at all times.

bugfix - tables not showing sometimes on admin pages

---

app/controllers/management/page_steps_controller.rb
app/javascript/pages/admin/edit-dashboard.js
app/views/management/page_steps/preview.html.erb
app/views/management/page_steps/title.html.erb

1. Move RW wysiwyg to preview, instead of under details 
2. Implement new dashboard layout for admin page preview
@santostiago moved the content editor from title to `/page_steps/preview` for new dashboard.
Could you make sure we accept the data on that step when saving ? `site_page[content]`
https://www.pivotaltracker.com/story/show/157696001

move RW wysiwg logic, new dashboard layout for admin preview

---

app/javascript/pages/management/widgets/EditWidgetPage.js
app/javascript/pages/management/widgets/NewWidgetPage.js

When the textarea of the advanced mode is empty, the preview fails and displays an error in the console. To prevent this, the preview is only shown if the widget config contains a "data" object.
To test this PR, go to http://localhost:3000/management/sites/base-site/widget_steps/new, select a dataset and choose the advanced mode. You shouldn't see any error in the console.

Widget creation/edition: remove an error from the console

---

app/assets/stylesheets/components/shared/c-loading-spinner.scss
app/assets/stylesheets/components/shared/c-toggle-switcher.scss
app/assets/stylesheets/layouts/management/l-widget-creation.scss
app/javascript/components/shared/ToggleSwitcher/index.js
app/javascript/components/shared/ToggleSwitcher/toggle-switcher.component.js
app/javascript/pages/management/widgets/EditWidgetPage.js
app/javascript/pages/management/widgets/NewWidgetPage.js

This PR brings several enhancements to the widget creation/edition:
1. The button to switch between the "standard" and advanced mode has been redesigned and put closer to the widget-editor.
2. When the user switches between the "standard" and advanced mode, the wysiwyg gets pre-populated with the widget of the editor.
3. When editing a "standard" widget, the user has the possibility to convert it with advanced mode (no going back).
Create or edit "standard"/advanced widgets.
1. [Pivotal task #1](https://www.pivotaltracker.com/story/show/158860215)
2. [Pivotal task #2](https://www.pivotaltracker.com/story/show/158860139)
3. [Pivotal task #3](https://www.pivotaltracker.com/story/show/158860075)

Improvements to the widget creation/edition

---

app/assets/stylesheets/components/shared/c-table.scss
app/javascript/components/table/Confirm.js
app/javascript/components/table/TableActions.js
app/javascript/components/table/index.js

Created a new modal for our delete table row logic, this is because there is currently a bug that does not prevent the default action on our table deletion links.  (known react issue on regular links) So even if you cancel the action, it still removes the item.
this is a description of the issue: https://medium.com/@ericclemmons/react-event-preventdefault-78c28c950e46
We need to use a _traditional link_ for the action to get triggered by rails. so capsulated the link inside a simple modal window instead.

Fix for delete row bug 

---

config/webpack/production.js

we are running out of memory on our staging servers, I think one of the reasons is that we are inlining our source maps. This causes the heap to explode! and as its all cashed and store in memory we are killing the server at this point.

add correct sourcemap and env settings to webpacker

---

app/assets/stylesheets/components/shared/c-content.scss
app/assets/stylesheets/components/shared/c-vizz-wysiwyg.scss

This pr adds: 
New quotation style. Removed the grey border from before and bumped the font size. Also made sure the same style is included for the open content V2 pages.
Also, the blockquote styles from previous versions where never used. we needed to important them :(

fix quotation styles for open content and home pages

---

app/assets/stylesheets/components/shared/c-dashboard.scss
app/controllers/site_page_controller.rb
app/javascript/components/shared/Dashboard/dashboard.actions.js
app/javascript/components/shared/Dashboard/dashboard.component.js
app/javascript/components/shared/Dashboard/dashboard.reducer.js
app/javascript/components/shared/Dashboard/dashboard.selectors.js
app/javascript/components/shared/Dashboard/index.js
app/views/site_page/dashboard_v2.html.erb

This PR updates which metadata in shown in the public dashboards and in which language.
By default, it tries to display the metadata in the language selected by the user (Transifex), but can default to the site's default language if none is available. As a last attempt, the metadata of any another language is picked (again, if any).
Two flows must be tested:
1. The correct language is picked
2. All the metadata is displayed
1. Create a site with any default language, for example «en», and allow translations in an other, for example «es».
2. Create a dataset and edit its metadata by adding a value for each field, in each language.
3. Create a widget for that dataset.
4. Create a dashboard based on that dataset and widget.
5. Open the dashboard locally and click on the info button below the …

Display correct metadata information in dashboards

---

app/assets/javascripts/dispatchers/managementDispatcher.js

This PR fix the bug of not having **Quick Links** dropdown on `/management`.
Open the `/management` route:
1. Quick Links dropdown should be displayed.
[Task](https://www.pivotaltracker.com/story/show/169265873)

Fix(#169265873): Show quick links dropdown on management.

---

app/views/management/page_steps/map.html.erb

This PR removes the second arrow from map version select.
1. Open a site with pages of type map or create a new map page.
2. Go to the map tab/step
3. Map version select should only display one arrow.
[Task](https://www.pivotaltracker.com/story/show/169193081)

Fix(#169193081): Remove double arrow from map version select.

---

app/javascript/components/shared/Dashboard/dashboard.helpers.js
app/javascript/components/shared/Dashboard/dashboard.selectors.js

This PR makes sure the dashboards always display the most relevant metadata available. Instead of just checking if a metadata exists in a specific language, we now also check if it's not empty, in which case we would fallback to a different one.
In order to test the changes locally, you must make the following temporary change first: in `app/javascript/components/shared/Dashboard/dashboard.component.js`, replace `componentDidMount` by:
```js
componentDidMount() {
const { setSelectedLanguage } = this.props;
setSelectedLanguage('fr');
}
```
Note that we set «fr» as the language. This means that the metadata of the dashboard will be displayed in French, if it exists and it is not empty.
Then, you need to pick a dataset for which you can add metadata in several languages in the management …

Make sure to always pick most relevant metadata for the dashboards

---

app/assets/stylesheets/components/front/c-header.scss

Make the height of the logo 85px. 50px + 5px + 30px (menu + flag + sub-menu).
1. Open one of the sites that had this logo height bug.
2. Logo should have correct height now.
[Task](https://www.pivotaltracker.com/story/show/169399550)

Fix logo height for desktop.

---

app/javascript/pages/admin/open-content-preview.js
app/javascript/pages/admin/open-content.js
app/javascript/pages/home.js
app/javascript/pages/static.js

This PR fixes a bug where empty pages (Open Content and Homepage) couldn't be edited anymore or even viewed.
_These are the instructions for the Open Content type of page (which are the ones reported to fail in the task), but the same process can be applied to the Homepage type of page._
1. Open the management section of a local site (using your local DB)
2. Click the «New page» button of the header
3. Click «Continue» at the «Position» step
4. Give a name, a description and a URI of your choosing and click «Continue»
5. Select «Open Content» as the type of page
6. Click «Save» at the «Content» step, without making any change to the page
7. Click «Publish» at the «Preview» step
8. Find the page in the list and click its edit button
9. Go directly to the «Content» step
Make sure the …

Fix a bug where empty pages can't be edited or viewed

---

app/controllers/admin/site_steps_controller.rb
app/models/site_page.rb
app/models/site_setting.rb
app/views/admin/site_steps/style.html.erb
app/views/front/_menu.html.erb

This PR creates a admin -> style -> header option for display or hide login.
1. For a local site go to Admin -> Style -> Header
2. You should see a new **Login** option.
3. You can choose show or hide and save.
4. The site should display or omit the login item accordingly.
[Task](https://www.pivotaltracker.com/story/show/168435693)

Add login enabled field to header settings.

---

app/assets/stylesheets/layouts/admin/l-site-creation.scss
app/models/site_setting.rb
app/views/admin/site_steps/style.html.erb
app/views/layouts/admin.html.erb
app/views/shared/_info_template.html.erb
config/locales/en.yml

This PR adds description messages for admin site_steps styles.
1. Open the style tabs in the admin settings for a site.
2. It should display an icon for information on each field.
3. It should display a tooltip on hover for all of these icons.
[Task](https://www.pivotaltracker.com/story/show/169580379)

Add a description for the site customization settings

---

app/assets/stylesheets/front/_base-theme-ind.scss

This PR:
* Hide measurement tool from map for India template
1. Go to a site map with version 1.4.2 and India template selected.
2. Measurement tool should not appear, only zoom in and out.
[Task](https://www.pivotaltracker.com/story/show/169761868)

feat(#169761868): Hide measurement tool for India template.

---

app/javascript/components/shared/Dashboard/dashboard.helpers.js

This PR fixes a bug where the dashboards would crash if no metadata would be available in the user's language.
1. Create a dashboard with any dataset (optional)
2. Open the dashboard's public page
Since Transifex is not run locally, the selected language will be `''`. As a consequence, there won't be any metadata corresponding to this empty string.
If the dashboard is correctly displayed, then this PR fixes the issue.
[Task](https://www.pivotaltracker.com/story/show/169919468).

Fix a bug where the dashboard could crash

---

app/assets/stylesheets/components/shared/c-vizz-wysiwyg.scss

This PR fixes an issue where the font style dropdown menu of the wysiwyg's floating menu might be partially hidden at the bottom.
<p align="center">
</p>
If we would to increase the `z-index` value of the floating menu, it would overlap the action bar that is located at the bottom of the screen, so instead, this PR adds a sufficiently big margin at the bottom of the wysiwyg.
1. Follow the first few steps to create a new Open Content page
2. At the «Content» step, add a new text block and paste a few paragraphs of text
3. Select a word of the last line of content
4. Click on the font style dropdown
Make sure you're able to see all the options of the dropdown (scrolling might be required).
[Task](https://www.pivotaltracker.com/story/show/169881213).

Fix an issue where some parts of the wysiwyg might not be visible

---

app/javascript/helpers/api.js

**⚠️ This PR depends on #381. You might not be able to test it without the fix provided by #381.**
This PR fixes an issue where the user wouldn't be able to download the data associated with a dashboard in Chrome.
<p align="center">
</p>
This would happen if the user would filter the dashboard using a numeric column. The reason being that the download URL would contain a “<” sign and [Chrome blocks URLs that contain it](https://www.chromestatus.com/feature/5735596811091968).
**Using Chrome:**
1. Create a dashboard based on a dataset that contains at least one numeric column (optional)
2. Open the public dashboard
3. Add a filter based on a numeric column, and move the left-side handle toward the centre
<p align="center">
</p>
4. Click «Apply filters»
5. Below the widget, click the button …

Fix a bug preventing the user from downloading filtered datasets in Chrome

---

app/controllers/management/page_steps_controller.rb

Fix the bug on `Management::PageStepsController` to ensure that it uses information of the session between the different steps.
1. Edit an existing page (map page for example)
2. Change the position of the page and click continue.
3. Change details of the page and click continue.
4. Make new changes and save
The information of the previous steps (position and details) should be saved.
[https://www.pivotaltracker.com/story/show/168644708](https://www.pivotaltracker.com/story/show/168644708)

Fix bug with removes session data between steps

---

app/models/site_page.rb

Update the children's URL when a change on the URI is made on pages.
1. Modify the URI of a page which has some pages as children.
2. Check that the URL of the children has changed with the new URI.
Another test that should be done is to update a parent page which has multiple levels of children.
[https://www.pivotaltracker.com/story/show/169753760](https://www.pivotaltracker.com/story/show/169753760)

Update children url when uri or url is changed

---

.travis.yml
app/controllers/admin/site_steps_controller.rb
app/interactors/site_steps/update_logic/name_step.rb

This PR fixes two bugs on the site creation:
- Avoid the 500 HTTP error when a context is not selected
- Mark the first route as the main one when we click on the continue button
Two tests should be done:
- No context is selected
1. Create a new site
2. Complete all steps until context and click to Continue without selecting one.
As a result, you can continue with the Settings step
- Multiple URL are specified for the site
1. Create a new site
2. Fill the main URL and another one as an alternative
3. Continue with the following steps
4. Access to the main URL and check that the content is correct
5. Access to the alternative URL and check that it is redirected to the main URL
[https://www.pivotaltracker.com/story/show/170507258](https://www.pivotaltracker.com/story/show/170507258)

Fix bug with additional uri for sites

---

package.json
yarn.lock

The advanced editor would crash when editing specific widgets because the `VegaChart` component of the [widget-editor](github.com/resource-watch/widget-editor) would crash itself. This PR addresses the issue by updating the widget-editor to its latest version, which [fixes the bug](https://github.com/resource-watch/widget-editor/blob/develop/CHANGELOG.md#v146---23012020).
1. Open `/management/sites/base-site/widget_steps/c1f84743-9373-4a64-96d3-0e72c7ef184a/edit`
2. Click the “Continue” button
The app must not crash and you must be able to see the widget.
No tracked.

Prevent the advanced editor from crashing when editing specific widgets

---

app/javascript/pages/admin/edit-dashboard.js

This PR fixes an issue where the text elements of the dashboards would be narrower in the wysiwyg, affecting their alignment.
1. Open or create a dashboard page
2. Go to the Preview step
3. Add a text block with some content (a few lines)
4. Center the text by selecting it and choosing the alignment option from the floating menu
Make sure the text is correctly centred and that it can reach both sides of the layout.
[Task](https://www.pivotaltracker.com/story/show/168355626).

Fix a text alignment issue in the dashboards

---

app/assets/stylesheets/layouts/management/l-widget-creation.scss
app/javascript/containers/ManagementDatasetMetadata.js
app/javascript/pages/management/widgets/EditWidgetPage.js
app/javascript/pages/management/widgets/NewWidgetPage.js
app/javascript/redactions/management.js

This PR removes the widget's caption field from all the UI.
For the widget-editor, we use a temporal hack to hide it. It will be completely removed in v2.
1. Click the button to create a new widget
2. Select a dataset and click “Continue”
3. Give the widget a name and click “Continue”
In the widget-editor, make sure there's no caption field display below the title one.
4. Click the “Advanced editor” tab
Make sure there's no “Caption” field above the JSON editor.
5. Repeat the steps 1-4 with the edit page
Comment on [this task](https://www.pivotaltracker.com/story/show/170235238/comments/211121321).

Remove the widget's caption field from the UI

---

app/assets/javascripts/routers/management/MapStepRouter.js

This PR allows the user to edit the HTML of the wysiwygs of the “Narrative” and “Alternative narrative” fields of the map configurations.
<p align="center">
</p>
1. Go to the management section of any site
2. Edit the map page
3. Click the “Map” tab
4. Go to the “Narrative” field and type some content
5. Click the last icon of the toolbar (the “Code view” one)
The content of the wysiwyg should be displayed as HTML.
6. Repeat the step 4-5 for the “Alternative narrative” field
The content of the wysiwyg should be displayed as HTML.
[Task](https://www.pivotaltracker.com/story/show/168500479).

Map editor: allow the user to edit the HTML of the wysiwygs
