Vizzuality/forest-atlas-landscape-cms

app/models/site.rb, app/models/site_template.rb, db/migrate/20160705085336_rename_template_model.rb, db/schema.rb, db/seeds.rb
=> Rename template model

Procfile, db/migrate/20160617084439_create_sites.rb, db/migrate/20160705085336_rename_template_model.rb, package.json
=> Heroku changes

Gemfile, Gemfile.lock, app/controllers/admin/sites_controller.rb, app/controllers/admin/users_controller.rb, app/controllers/management/pages_controller.rb, app/serializers/page_serializer.rb, app/serializers/site_serializer.rb, app/serializers/site_template_serializer.rb, app/serializers/user_serializer.rb, app/views/admin/routes/index.json.jbuilder, app/views/admin/routes/show.json.jbuilder, app/views/admin/site_templates/index.json.jbuilder, app/views/admin/site_templates/show.json.jbuilder, app/views/admin/sites/index.json.jbuilder, app/views/admin/sites/show.json.jbuilder, app/views/admin/users/index.json.jbuilder, app/views/admin/users/show.json.jbuilder, config/initializers/active_model_serializer.rb
DO NOT MERGE - Peding merge + rebase of https://github.com/Vizzuality/forest-atlas-landscape-cms/pull/11
=> [Pending rebase] Feature/management apis

app/controllers/admin/sites_controller.rb, app/controllers/admin/users_controller.rb, app/models/site.rb, app/models/user.rb, app/models/user_site_association.rb, app/serializers/page_serializer.rb, app/serializers/site_serializer.rb, app/serializers/user_serializer.rb, app/views/admin/sites/_form.html.erb, app/views/admin/users/_form.html.erb, db/migrate/20160808143633_create_user_site_associations.rb, db/schema.rb, lib/tasks/sample.rake
=> Add User to Site relationship

app/controllers/home_controller.rb, app/controllers/page_controller.rb, app/router/dynamic_router.rb, app/views/home/index.html.erb, app/views/page/analysis_dashboard.html.erb, app/views/page/dynamic_indicator_dashboard.html.erb, app/views/page/map.html.erb, app/views/page/open_content.html.erb, db/migrate/20160819102119_convert_page_type_to_int.rb, db/schema.rb, spec/router/dynamic_router_spec.rb
Implement different templates per content type
=> Implement different templates per content type

app/assets/stylesheets/components/front/c-header.scss, app/views/front/_menu.html.erb
Add padding to subsections on mobile menu.
=> Change mobile menu styles

app/assets/javascripts/templates/shared/notification.hbs, app/assets/javascripts/views/shared/notificationView.js, app/assets/stylesheets/admin/_settings.scss, app/assets/stylesheets/components/shared/c-notification.scss, app/assets/stylesheets/management/_settings.scss
This PR adds a fully accessible notification component to display success, warning or error messages.
The component has the following options:
* notification message
* notification type
* whether or not the notification can be closed
* auto-close timer
=> Adds the notification component

app/assets/stylesheets/components/shared/c-steps-bar.scss, app/controllers/admin/site_steps_controller.rb, app/views/admin/site_steps/_header.html.erb
This PR adds the steps bar component and integrate it in the site creation process.
@santostiago Could you check the changes I made to the controller are correct?
=> Adds the steps-bar component

app/assets/javascripts/templates/admin/flag-colors.hbs, app/assets/javascripts/views/admin/flagColorsView.js
This PR makes the choice of flag colours optional for the Forest Atlas template.
[Pivotal task](https://www.pivotaltracker.com/story/show/133992975)
=> Makes the flag colors optional on the FA template

app/controllers/site_page_controller.rb, app/router/dynamic_router.rb
I've created a route for the /report.html but I'm not sure this is doing what's intended.
Do you mind checking if it's this the expected behaviour?
=> Create route for the /report

app/assets/stylesheets/components/shared/c-cards-list.scss, app/assets/stylesheets/layouts/management/l-page-creation.scss, app/views/management/page_steps/dataset.html.erb
This PR styles the dataset step of the dashboard creation process.
=> Styles the dataset step of the page creation

app/assets/stylesheets/components/shared/c-cards-list.scss, app/assets/stylesheets/layouts/management/l-page-creation.scss, app/views/management/page_steps/columns.html.erb, app/views/management/page_steps/filters.html.erb
This PR styles the "columns" step of the dashboard creation/edition process.
**It can't be merged before #98.**
=> Styles of the "columns" step of the page creation/edition

Capfile, Gemfile, Gemfile.lock, config/database.yml, config/deploy.rb, config/deploy/production.rb, lib/tasks/sample.rake
=> Capistrano config

config/environments/development.rb
It will only work in development environment.
=> Mutes assets pipeline log messages

app/controllers/admin/site_steps_controller.rb, app/controllers/admin/sites_controller.rb, app/controllers/admin/users_controller.rb, app/controllers/admin_controller.rb, app/controllers/management/page_steps_controller.rb, app/controllers/management/site_pages_controller.rb, app/controllers/management/static_page_controller.rb, app/controllers/management_controller.rb, app/views/admin/_header.html.erb, app/views/management/_header.html.erb, config/routes.rb
Admin and Management breadcrumbs
=> Admin and Management breadcrumbs

app/assets/stylesheets/_base.scss, app/assets/stylesheets/components/management/c-tree-structure.scss, app/assets/stylesheets/components/shared/c-action-bar.scss, app/assets/stylesheets/layouts/management/l-tabs.scss, app/views/management/datasets/index.html.erb, app/views/management/sites/structure.html.erb
I've removed a blue shadow when user click on some elements like "a", "button" and "input". I've changed layout styles for big screens.
=> removed blue shadow for focused elements, layout like design

app/assets/javascripts/routers/admin/SiteEditionRouter.js, app/assets/stylesheets/components/admin/c-centered-input.scss, app/controllers/admin/site_steps_controller.rb, app/views/admin/site_steps/settings.html.erb
=> Adding preview for existing logo

CHANGELOG.md, app/assets/javascripts/blots/imageBlock.es6, app/assets/javascripts/blots/imageBlock.js, app/assets/javascripts/blots/widgetBlock.es6, app/assets/javascripts/blots/widgetBlock.js, app/assets/javascripts/views/shared/wysiwygView.js, app/assets/stylesheets/components/management/c-wysiwyg.scss, app/assets/stylesheets/components/shared/c-content.scss
This PR lets the users add an optional caption to the images and widgets of the wysiwyg.
For the widgets only, the default caption is their description.
=> Possibility to add a caption to the images and widgets

CHANGELOG.md, app/assets/javascripts/dispatchers/managementDispatcher.js, app/assets/javascripts/routers/management/DatasetStepRouter.js, app/assets/javascripts/views/management/widgetsModalView.js, app/assets/javascripts/views/shared/tableView.js, app/controllers/management/page_steps_controller.rb, app/controllers/management/widget_steps_controller.rb, app/models/context.rb, app/models/dataset_setting.rb, app/models/site.rb, app/services/dataset_service.rb, app/views/management/page_steps/dataset.html.erb, app/views/management/widget_steps/dataset.html.erb, lib/tasks/sample.rake
This PR brings two changes to the lists of datasets:
* GFW's datasets are now listed
* the datasets aren't grouped by contexts anymore and are searchable
=> Improves the lists of datasets

app/assets/javascripts/templates/shared/dropdown-selector.hbs, app/assets/javascripts/views/shared/dropdownSelectorView.js, app/assets/javascripts/views/shared/quickLinksView.js, app/assets/stylesheets/components/shared/c-dropdown-selector.scss
Adds an option to the dropdown selector view to support dropdown options separators.
=> Feature: dropdown separator

app/assets/stylesheets/components/front/c-cover.scss, app/assets/stylesheets/layouts/admin/l-site-creation.scss, app/controllers/admin/site_steps_controller.rb, app/models/site_setting.rb, app/views/admin/site_steps/settings.html.erb, app/views/front/_cover.html.erb, db/migrate/20170222110701_add_attribution_link_and_attribution_label_to_site_settings.rb, db/schema.rb
This PR adds support to attribution links and labels for cover images.
=> Feature: cover attribution

app/assets/javascripts/templates/admin/urls-input.hbs
@santostiago do we need any change on the backend? please let me know
=> Remove protocol on URL input

CHANGELOG.md, app/controllers/admin/site_steps_controller.rb, app/models/site.rb
Marks removed routes for deletion when saving parent object
=> Fixes deleting site urls

app/assets/stylesheets/components/front/c-cover.scss
This PR changes the header fade out effect, and the header title position.
=> feat: header fade effect

CHANGELOG.md, app/assets/stylesheets/components/shared/c-content.scss
This PR changes size and disposition of arcgis embed maps.
=> feat: map embed styles

config/deploy.rb
@agnessa I shamelessly copied your code. should work, but I didn't actually test it
=> Update site settings on deploy

CHANGELOG.md, README.md, app/assets/javascripts/routers/front/DashboardRouter.js, app/assets/javascripts/routers/management/PreviewStepRouter.js, app/assets/javascripts/templates/front/chart-widget.hbs, app/assets/javascripts/templates/shared/table.hbs, app/assets/javascripts/views/shared/chartWidgetView.js, app/assets/javascripts/views/shared/mapWidgetView.js, app/assets/stylesheets/components/shared/c-button.scss, app/assets/stylesheets/layouts/shared/l-analysis-dashboard.scss, app/controllers/site_page_controller.rb, app/views/management/page_steps/preview.html.erb, app/views/site_page/analysis_dashboard.html.erb, db/migrate/20170329090135_add_visible_to_widgets.rb, db/schema.rb, lib/tasks/sample.rake
- Add toggleVisibility button to preview in Analysis page
- Add visible attribute to widget
- Hide the graph in the page when visible is on
- Add a sample user 
- Update readme in the setup
=> Feature toggle visibility widgets

app/assets/javascripts/templates/front/charts/bar.hbs, app/assets/javascripts/templates/front/charts/line.hbs, app/assets/javascripts/templates/front/charts/pie.hbs, app/assets/javascripts/templates/front/charts/scatter.hbs, app/assets/javascripts/templates/front/charts/vegaTheme.hbs
- Fixes broken scatter plot chart.
- Includes the x axis in the scatter, line and bar charts.
- Changes labels font weight.
- Removes pie chart marks' labels.
- Includes colorRange into the charts and updates the theme.
- Corrects the axes' titles position.
=> Fix: vega charts improvements

app/controllers/context_steps_controller.rb
https://www.pivotaltracker.com/story/show/138315937
=> Permitted owners are either admins or managers of previously selected sites

app/assets/javascripts/routers/management/PagesRouter.js, app/assets/javascripts/templates/shared/table.hbs, app/assets/javascripts/views/shared/tableView.js, app/assets/stylesheets/components/shared/c-table.scss
This PR includes the following:
- Trickles down the enabled prop to the tableview.
- Greys out disabled pages.
=> Feat: grayed out disabled pages

app/assets/javascripts/templates/shared/table.hbs
This PR fixes the following issue(s):
- Removes extra column created by the `enabled` flag added in #206 .
=> Fix: removes extra column

CHANGELOG.md, app/controllers/admin/sites_controller.rb, app/controllers/management/contexts_controller.rb, app/controllers/management/datasets_controller.rb, app/controllers/management/site_pages_controller.rb, app/controllers/management/sites_controller.rb, app/controllers/management/widgets_controller.rb, app/models/page.rb, app/models/route.rb, app/views/admin/site_steps/finish.html.erb, app/views/management/steps_shared/_finish_footer.html.erb
https://www.pivotaltracker.com/story/show/143862299
=> Prepend scheme to host if missing

CHANGELOG.md, app/assets/javascripts/helpers/notifications.js, app/assets/javascripts/routers/front/DashboardRouter.js
This PR includes the following:
- Checks if the saved state widgets match in visibility and type to the one currently available, if not, displays a warning.
=> feat: warn of unavailable bookmarks

app/models/site_page.rb
fix for https://appsignal.com/vizzuality/sites/58da5f06b504f542f5c3123b/incidents/55
=> Only compare positions if both present

app/router/dynamic_router.rb, config/routes.rb
https://appsignal.com/vizzuality/sites/58da5f06b504f542f5c3123b/incidents/13
=> Fixed exception when requesting /not_found

app/controllers/management/site_pages_controller.rb
https://appsignal.com/vizzuality/sites/58da5f06b504f542f5c3123b/incidents/57
=> Force 404 if site not found

CHANGELOG.md, app/controllers/admin/site_steps_controller.rb, app/models/site_setting.rb, app/views/admin/site_steps/settings.html.erb, app/views/layouts/application.html.erb, lib/tasks/update_site_settings.rake
[Not really WIP, just pending client approval]
=> Add configurable transifex api key to site settings

CHANGELOG.md, app/assets/javascripts/routers/management/DatasetsRouter.js, app/controllers/management/datasets_controller.rb, app/models/dataset.rb, app/services/dataset_service.rb, app/views/management/datasets/_metadata_form.html.erb, app/views/management/datasets/edit_metadata.html.erb, config/routes.rb
Adds an edit button on the list of datasets that allows to update existing metadata.
=> Allows to edit existing metadata

app/assets/javascripts/routers/management/DatasetStepRouter.js, app/assets/javascripts/routers/management/VisualizationStepRouter.js, app/assets/javascripts/views/shared/chartWidgetView.js, app/assets/stylesheets/components/shared/c-loading-spinner.scss
This PR includes:
- New loader inside the submit button in the dataset step of widget creation to notify the user that the dataset is being submitted.
- New loader inside the `ChartWidgetView` that appears when the chart is rendering.
=> feat: loading dataset values & widget chart view spinners

app/controllers/management/page_steps_controller.rb, app/services/dataset_service.rb, lib/tasks/sample.rake
This will make sure the admin works with datasets, also updating sample.rake with some up-to-date datasets, otherwise admin wont render
=> fix broken datasets logic

app/controllers/admin/map_versions_controller.rb, app/controllers/admin/sites_controller.rb, app/controllers/admin/users_controller.rb, app/javascript/components/containers/AdminTableView.js, app/javascript/components/containers/shared/AdminContainer.js, app/javascript/components/pages/admin/table-view.js, app/javascript/components/redactions/admin.js, app/views/admin/map_versions/index.html.erb, app/views/admin/sites/index.html.erb, app/views/admin/users/index.html.erb
now we are only using react for displaying tables!
=> remove all backbone table views!

app/javascript/components/Notification.js
This PR adds a new React component ,`Notification`, based on Backbone's notification component. The only missing "feature" is the animation when appearing and disappearing.
PS: this component will be used in the widget creation.
=> Migrate the Notification component to React

.gitignore, app/assets/stylesheets/components/shared/c-dashboard.scss, app/assets/stylesheets/components/shared/c-inputs-container.scss, app/controllers/site_page_controller.rb, app/javascript/components/CoverPage.js, app/javascript/components/WidgetReports.js, app/javascript/components/admin/table/index.js, app/javascript/containers/Cover.js, app/javascript/containers/PublicDashboard.js, app/views/layouts/application.html.erb, app/views/management/page_steps/title.html.erb, app/views/site_page/analysis_dashboard.html.erb, app/views/site_page/dashboard_v2.html.erb
This PR includes the new dashboard, resource watch WYSIWYG editor, and some general style improvements.
=> Bug fixes and improvements

README.md, app/assets/stylesheets/front/_base-theme-fa.scss, app/views/site_page/map.html.erb
https://www.pivotaltracker.com/story/show/156838990
also default to latest map builder version.
=> add map builder header on map page

app/views/admin/sites/_form.html.erb, app/views/admin/user_steps/contexts.html.erb, app/views/admin/user_steps/sites.html.erb, app/views/management/dataset_steps/connector.html.erb, app/views/management/dataset_steps/context.html.erb, app/views/management/dataset_steps/title.html.erb, app/views/management/page_steps/customization.html.erb, app/views/management/page_steps/title.html.erb
Remove all lorem ipsum sub headings
=> remove lorem ipsum content

app/assets/javascripts/views/front/languageSelectorView.js
Dropdowns now rendering the options !
And yeah, translating also 
https://www.pivotaltracker.com/story/show/156120391
=> fix transifex 

app/models/site.rb
Please review what is changed. And there should be a template for `CARPE` with which to generate each site's css.
=> Changed the generation of the templates' css to include carpe.

app/controllers/admin/user_steps_controller.rb, app/controllers/admin/users_controller.rb, app/views/admin/user_steps/_footer.html.erb, app/views/admin/users/index.html.erb
=> Added the edition of users

app/models/page_template.rb, lib/assets/privacy_policy_page.json, lib/tasks/sample.rake
Created the page template for privacy policy.
@tomasmoose please check the WYSIWYG cause the preview isn't exactly as it should be.
=> Added template page 'Privacy Policy' and a rake task to create them

app/assets/stylesheets/components/shared/c-content.scss, lib/assets/privacy_policy_page.json
We where using an old syntax for the policy page, updated now
=> update json syntax for policy page

app/assets/javascripts/admin.js, app/assets/javascripts/dispatchers/adminDispatcher.js
https://www.pivotaltracker.com/story/show/158299917
@santostiago
=> Fix admin navigation menu not showing

app/controllers/management/page_steps_controller.rb, app/controllers/site_page_controller.rb, app/enumerations/content_type.rb, app/javascript/containers/OpenContentPage.js, app/javascript/containers/StaticPage.js, app/javascript/pages/admin/open-content.js, app/javascript/pages/static.js, app/models/page.rb, app/models/site_page.rb, app/router/dynamic_router.rb, app/views/management/page_steps/open_content_v2.html.erb, app/views/management/page_steps/type.html.erb, app/views/site_page/open_content_v2.html.erb
Add new open content page type with the `vizz-wyswyg` logic. 
https://www.pivotaltracker.com/story/show/158020489
@santostiago could you make sure I didn't break anything as I modified the rails code here also, thanks!
=> new content page type

app/javascript/components/wysiwyg/WidgetBlockCreation.js, app/models/site_page.rb, app/views/management/page_steps/preview.html.erb
This PR removes the step to create a widget from the dashboard creation/edition flow.
=> Remove the widget steps of the dashboard creation

app/controllers/admin/map_versions_controller.rb, app/controllers/site_page_controller.rb, app/models/map_version.rb, app/views/admin/map_versions/_form.html.erb, app/views/site_page/map.html.erb, db/migrate/20180717142739_add_html_to_map_versions.rb, db/schema.rb
Tomas, before merging please make sure the frontend is working as it should.
Thank you
=> Added the html field to the map version

app/views/site_page/map.html.erb
bring back map version to the map template,
*note, we should take into account that there will be a new version published with the subscription event.
=> map custom html logic

app/javascript/components/CoverPage.js
https://www.pivotaltracker.com/story/show/159343730
=> fix page header titles for subpages

Dockerfile, DockerfileDev, Gemfile.lock, README.md
Make docker work again! 
Use node 8.x
Install yarn on disk
install node packages in the machine
=> dev docker fixes

app/assets/stylesheets/components/shared/c-vizz-wysiwyg.scss, app/javascript/components/wysiwyg/ImagePreview.js, app/javascript/components/wysiwyg/ImageUpload.js, package.json, yarn.lock
1. Now you can add captions to photos. Also added some styling and improvements to the form in general
2. You can now remove individual items within a column.
https://www.pivotaltracker.com/story/show/158860270
https://www.pivotaltracker.com/story/show/159142993
https://www.pivotaltracker.com/story/show/158860330
=> wysiwyg updates and improvements

app/assets/stylesheets/components/shared/c-content.scss, app/assets/stylesheets/components/shared/c-vizz-wysiwyg.scss, app/controllers/static_page_controller.rb, app/javascript/components/wysiwyg/WidgetBlock.js, app/models/widget.rb, app/services/widget_service.rb
This PR displays the title and caption (if any) of the widgets in the Open content pages.
<p align="center">
</p>
=> Open content: display the title and caption of the widgets

app/views/site_page/map.html.erb
=> change map version

app/models/site.rb, app/models/site_page.rb, lib/tasks/update_sites.rake
- Avoid setting black as the default colour for header-country-colours site setting
- Set default empty value for header-country-colours
=> Fix bugs on update sites templates

.gitignore, lib/tasks/create_default_template.rake, lib/tasks/map_config.json
Updated the `map_config.json` file and created a task to update the content of the map template pages to match this file.
The task should be run using: `rails templates:update_map_pages`.
=> Updated the template map config
